#generated by emake-0.3.3

EAPI=6
inherit cmake-utils

DESCRIPTION="10-Bands parametric equalizer with mono (M) and stereo (S) versions."
HOMEPAGE="http://eq10q.sourceforge.net"


LICENSE="GPL2"
SLOT="0"
KEYWORDS="amd64 ~x86 ~arm"
IUSE=""

RDEPEND=""
DEPEND="
	${RDEPEND}
"

S=${WORKDIR}/eq10q-2.2/

src_unpack() {
	unpack "/usr/local/portage/emake/distfiles/eq10q-2.2.txz"
}

src_configure() {
	local mycmakeargs=(
		-DCMAKE_INSTALL_PREFIX="/usr/lib/lv2"
	)
	cmake-utils_src_configure
}

